iLCSoft/LCIO

README.md
Configured Coverity scan, but defects not visible immediately due to:
```
While we review your project application you cannot view defects.
It takes about 1-2 business day to review your association with the project and to make sure project meets open source guidelines.
```
=> Add Coverity scan

.travis-ci.d/compile_and_test.sh
This now indicates properly that it's broken in the configuration stage
=> Put and statement between CI steps

src/cpp/include/UTIL/ILDConf.h
iLCSoft installation breaks (MarlinTrk) because lcio namespace is missing since it's coming from the [header file](https://github.com/iLCSoft/LCIO/blob/master/src/cpp/include/UTIL/CellIDDecoder.h#L18)
=> Add back CellIDDecoder.h 

src/cpp/include/UTIL/LCTrackerConf.h
Otherwise our reconstruction will not run
- LCTrackerConf: allow first field to be called "system"
=> For backward compatibility allow first field to be called system

.travis.yml
- Update to the CI system:
- Install directly cvmfs on base system, which removes the need for the parrot connector 
- Replace CernVM docker with plain docker
- This reduces the build run time from 15 min to 5 min
=> Remove the Parrot Connector and mount cvmfs directly

.travis-ci.d/coverity_scan.sh, .travis.yml
Modified the CI so that when triggered by a cron job (now it is set to weekly) it will do a Coverity scan.
This is a demo how all other packages are planned to be treated.
- Integate CI with Coverity scan via Travis cron jobs
=> Integrate with Coverity

src/cpp/include/UTIL/LCTrackerConf.h
multiple comparisons don't work that way, give warning in gcc62
- LCTrackerConf: bugfix for checks of encoding string field order
=> LCTrackerConf: make position order check working

examples/go/README.md, examples/go/read-event/main.go
This CL adds a simple Go-based example, based on the C++-rootDict one.
The example reads in a LCIO file and builds the histogram of the energy
of the (by default) skimmed mc particles.
Fixes iLCSoft/LCIO#20.
- add an example using `LCIO` from `Go`
=> examples/go: add a Go-based example

src/cpp/include/UTIL/CellIDDecoder.h
solves some static initialisation/cleanup warnings from valgrind
```
==9435==    at 0x4A08D73: operator new(unsigned long) (vg_replace_malloc.c:332)
==9435==    by 0x514AC96: void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) [clone .isra.97] (basic_string.tcc:219)
==9435==    by 0x5155925: __static_initialization_and_destruction_0 (CellIDDecoder.h:121)
==9435==    by 0x5155925: _GLOBAL__sub_I_LCTOOLS.cc (LCTOOLS.cc:1472)
==9435==    by 0x5176295: ??? (in .../lib/liblcio.so.2.9.0)
...
```
- CellIDDecoder: use static string instead of static pointer to string for defaultEncoding
=> CellIDDecoder: replace static pointer to string with static string

CMakeLists.txt, cmake/lcio.xml.in, src/aid/EVENT/SimCalorimeterHit.aid, src/cpp/include/IMPL/SimCalorimeterHitImpl.h, src/cpp/include/pre-generated/EVENT/SimCalorimeterHit.h, src/cpp/src/EXAMPLE/simjob.cc, src/cpp/src/IMPL/SimCalorimeterHitImpl.cc, src/cpp/src/SIO/SIOSimCalHitHandler.cc, src/cpp/src/UTIL/Operators.cc, src/java/hep/lcio/example/RecJob.java, src/java/hep/lcio/example/SimJob.java, src/java/hep/lcio/implementation/event/ISimCalorimeterHit.java, src/java/hep/lcio/implementation/sio/SIOSimCalorimeterHit.java
- add the step length to the MC-Contributions of the `SimCalorimeterHit`
- add method `SimCalorimeterHit::getLengthCont(int) ` to access it 
- only stored if `LCIO.CHBIT_STEP` is set (detailed shower mode)
- implemented in C++ and Java (!?)
- updated version number to v02-11
- fixed some versions in ./cmake/lcio.xml.in
=> add SimCalorimeterHit::getLengthCont() (step length)

src/cpp/include/CPPFORT/HEPEVT.h, src/cpp/include/UTIL/CellIDDecoder.h, src/cpp/include/UTIL/CollectionParameterMap.h, src/cpp/include/UTIL/LCFixedObject.h, src/cpp/include/UTIL/PIDHandler.h, src/cpp/src/EXAMPLE/CalibrationConstant.h, src/cpp/src/UTIL/CollectionParameterMap.cc, src/cpp/src/UTIL/PIDHandler.cc
- Remove using namespace from header files
=> Remove using namespace from header files

src/cpp/include/LCRTRelations.h, tests/CMakeLists.txt
- Refactored `LCRTRelations` class and friends
- Removed global map for extension deletion
- Introduced mechanism to store extension as `shared_ptr<void>` in a map
- Fixes thread safety issue at the cost of introducing a small memory overhead per added extension
- Exclude extension map from ROOT dictionaries I/O
- because `std::type_index` has no default constructor
- Activated compilation of runtime extensions unit test
=> [LCIO-MT] Library thread safety cleanup : LCRTRelations

src/cpp/CMakeLists.txt, src/cpp/include/IOIMPL/LCEventIOImpl.h, src/cpp/include/IOIMPL/LCRunHeaderIOImpl.h, src/cpp/include/MT/LCReader.h, src/cpp/include/MT/LCReaderListener.h, src/cpp/include/MT/Types.h, src/cpp/src/EXAMPLE/lcio_parallel_processing.cc, src/cpp/src/MT/LCReader.cc
- Implemented `MT::LCReader` for multi-threading usage
- Uses `std::shared_ptr` to manage LCEvent and LCRunHeader after record reading
- Can read records one by one using `readNextRecord()`
- Listeners are directly pass in `readStream()` as argument to avoid possible late registration of additional listeners
- Added example for parallel processing with MT::LCReader
- Simple scheduler to run task in parallel over n events
- Join event processing task on run header callback
- Can specify max number of threads N to use with:
```shell
export LCIO_MAX_THREADS=N
```
=> [LCIO-MT] MT::LCReader and parallel processing example

src/cpp/src/IMPL/LCIOExceptionHandler.cc
- Remove `std::set_unexpected` and `std::set_terminate` which were removed in C++17
=> Remove deprecated set_unexpected and set_terminate

src/cpp/src/IMPL/LCIOExceptionHandler.cc
- re-introduce `std::set_terminate` in `LCIOExceptionHandler`, which is not deprecated in c++17
=> re-introduce set_terminate in LCIOExceptionHandler

src/cpp/src/UTIL/lXDR.cc
- fix building for MacOS 10.14
- rm superfluous `#include "/usr/include/sys/types.h"` 
(thanks P.Mato)      
=> fix building for MacOS 10.14

cmake/ilcsoft_default_rpath_settings.cmake
-  Use "Always full RPATH" as as implemented in ROOT
The problem is that the build location is placed into LC_RPATH
```
objdump -x /Users/Shared/cvmfs/sft.cern.ch/lcg/releases/LCIO/02.13-28ace/x86_64-mac1015-clang110-opt/lib/liblcio.2.13.0.dylib
cmd LC_RPATH
cmdsize 104
path /Users/mato/Development/releases/97rc3python3/LCIO/02.13/x86_64-mac1015-clang110-opt/lib (offset 12)
```
but on mac it should be
```
Load command 17
cmd LC_RPATH
cmdsize 32
path @loader_path/../lib (offset 12)
```
all is crucial for LCG releases of mac binaries and downstream key4hep developments.
=> Update rpaht settings

src/python/pyLCIO/base/HandleExceptions.py
- Small changes in HandleExceptions.py  to cope with the change of API foreseen for ROOT 6.22
=> Cope with API change in PyROOT

src/python/pyLCIO/base/HandleExceptions.py
- Fine tune the latest fix to cope with new PyROOT to use old API for versions 6.20.X
resolves #76
=> PyROOT fix

src/cpp/include/SIO/SIOReader.h, src/cpp/src/SIO/SIOLCGenericObjectHandler.cc
- Fixed LCGenericObject collection flag IO writing
- Fixed virtual override warning in SIOReader 
=> LCGenericObject IO fix

sio/CMakeLists.txt
- fix bug in build dependency, affecting only build on large number of cores
If you build on many cores, you would start building things that need `libsio` before this was available and you get into this situation
```
[ 42%] Building CXX object lcio/CMakeFiles/lcio.dir/src/SIO/LCIORandomAccessMgr.cc.o
[ 42%] Building CXX object lcio/CMakeFiles/lcio.dir/src/SIO/RunEventMap.cc.o
make[2]: *** No rule to make target 'lib/libsio.so.0.0.2', needed by 'lib/liblcio.so.2.14.2'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object lcio/CMakeFiles/lcio.dir/src/MT/LCWriter.cc.o
[ 43%] Building CXX object lcio/CMakeFiles/lcio.dir/src/MT/LCReader.cc.o
[ 44%] Linking CXX shared library ../lib/libsio.so
[ 44%] Built target sio
``` 
bug fix …
=> fix bug in build dependency

src/cpp/include/SIO/SIOReader.h, src/cpp/src/SIO/SIOReader.cc
- fix memory leak in SIOReader
- delete previous Event and RunHeader before reading a new one
- this restores the old expected behavior of the `IO::LCReader`
- for parallel event reading one needs to use the `MT::LCReader` directly and
handle the memory accordingly (e.g. via use of std::unique_ptr)
- see [$LCIO/src/cpp/src/EXAMPLE/lcio_parallel_processing.cc](../src/cpp/src/EXAMPLE/lcio_parallel_processing.cc)
- fixes #97 and #98 
=> fix memory leak in SIOReader

examples/cpp/delphes2lcio/README.md, examples/cpp/delphes2lcio/examples/delphes2lcio.cfg, examples/cpp/delphes2lcio/examples/fill_histos_lcio.C, examples/cpp/delphes2lcio/examples/higgs_recoil_plots.C, examples/cpp/delphes2lcio/examples/higgs_recoil_plots_fast.C, examples/cpp/delphes2lcio/include/DelphesLCIOConfig.h, examples/cpp/delphes2lcio/src/DelphesLCIOConverter.cc, src/cpp/CMakeLists.txt, src/cpp/include/UTIL/LCIterator.h, src/cpp/include/UTIL/ProcessFlag.h, src/cpp/src/UTIL/ProcessFlag.cc
- improve the `delphes2lcio` tool
- changes some default collection names
- Electrons/ Muons/ Photons -> IsolatedElectrons / IsolatedMuons / ...
- MCParticle -> MCParticles
- update all examples and Readme.md accordingly
- add event params: crossSection and ProcessID as available in Delphes
- add method `ProcessFlag decodeMCTruthProcess(const EVENT::LCCollection*) `
- with first example implementation -> needs iteration
- call this in `delphes2lcio`
- use `const EVENT::LCCollection*` in `UTIL::LCIterator`
=> improve the delphes2lcio tool

examples/cpp/delphes2lcio/README.md, examples/cpp/delphes2lcio/src/DelphesLCIOConverter.cc, src/cpp/include/UTIL/ProcessFlag.h, src/cpp/src/UTIL/ProcessFlag.cc
- make delphes2lcio compatible w/ LCIO 2.14 again
- by not calling `ProcessFlag::decodeMCTruthProcess()`
- add `higgsss` and `unknown` to `ProcessFlag`
- update logic in `ProcessFlag::decodeMCTruthProcess()` (from J.List, DESY)
=> Improve delphes v1

src/cpp/src/UTIL/ProcessFlag.cc
- fix `ProcessFlag::decodeMCTruthProcess()`
- remove ISR photons in final state for DBD 250 GeV files
=> fix ISRs in ProcessFlag::decodeMCTruthProcess

README.md, setup.sh, src/cpp/include/MT/LCWriter.h, src/cpp/src/IOIMPL/LCFactory.cc, src/cpp/src/TESTS/test_splitting.cc, tests/CMakeLists.txt
- fix the compression level:  use zlib default compression again
in `SIOWriter` and `MT::LCWriter`
- update the build instructions with ROOT in README.md
- and set LD_LIBRARY_PATH in setup.sh
=> Patch lcio v02 15

examples/cpp/delphes2lcio/README.md, examples/cpp/delphes2lcio/examples/delphes2lcio.cfg, examples/cpp/delphes2lcio/include/DelphesLCIOConfig.h, examples/cpp/delphes2lcio/include/DelphesLCIOConverter.h, examples/cpp/delphes2lcio/src/DelphesLCIOConfig.cc, examples/cpp/delphes2lcio/src/DelphesLCIOConverter.cc
- add optional event meta data in delphes2lcio
- meta data like cross sections can be added via the configuration file
- see [../examples/cpp/delphes2lcio/README.md](../examples/cpp/delphes2lcio/README.md) for details
=> add optional event meta data in delphes2lcio

examples/cpp/delphes2lcio/src/DelphesLCIOConverter.cc, src/cpp/src/UTIL/ProcessFlag.cc
- fix in UTIL::ProcessFlag::decodeMCTruthProcess
- protection for events where nMCParticles < 10
- fix also, independently in delphes2lcio
=> Fix decode mc truth process

examples/cpp/delphes2lcio/README.md, examples/cpp/delphes2lcio/examples/delphes2lcio.cfg, examples/cpp/delphes2lcio/include/DelphesLCIOConfig.h, examples/cpp/delphes2lcio/include/DelphesLCIOConverter.h, examples/cpp/delphes2lcio/src/DelphesLCIOConfig.cc, examples/cpp/delphes2lcio/src/DelphesLCIOConverter.cc
- delphes2lcio: add optional extra PFO collections
- add by default BCalPFOs created from branch BCalPhotons
=> add optional extra PFO collections in delphes2lcio

examples/cpp/delphes2lcio/src/DelphesLCIOConverter.cc
- fix in `delphes2lcio` example
- avoid NANs in jet 4-momenta by using zero mass hyptheses
- NB: the mass is still set independently to the specified value (following PandoraPFA) 
=> fix nan's in jet 4-momenta (delphes2lcio)

src/cpp/include/LCRTRelations.h
- make compatible w/ clang 12 (on MacOs)
- remove const from map key in LCRTRelations
- map keys are immutable anyways 
=> remove const from  map key in LCRTRelations

src/cpp/CMakeLists.txt, src/cpp/src/EXAMPLE/lsh.cc
- the lsh examples is somewhat out-of-date
and would need some work
- does not build w/ newer libreadline
- has issues w/ direct access 
- ...
- leave the code in the repo, marked as deprecated, in case someone wants to modernize it
- no longer build the out-of-date lsh example
=> no longer build lsh example

src/cpp/include/UTIL/ProcessFlag.h
- fix in `UTIL::ProcessFlag`
- fixed const correctness and make the operator<<(ostream) inline
=> ProcessFlag: fixed constness and inline operator<<

config/aid.includes.cpp.properties, config/aid.types.cpp.properties, src/aid/EVENT/LCEvent.aid, src/aid/EVENT/LCObject.aid, src/aid/EVENT/Vertex.aid, src/cpp/include/Exceptions.h, src/cpp/include/UTIL/PIDHandler.h
- fix some warning:
- deprecated dynamic exception specifications in Exceptions
- fix the build from generated C++ files
=> Fix deprecated exception warnings

src/cpp/src/SIO/LCIORandomAccessMgr.cc
- Fixed skip record condition in Random Access Manager
Fixes #128
=> Random access manager fix

.github/workflows/linux.yml, src/cpp/include/CPPFORT/deprecation.h, src/cpp/include/CPPFORT/lccah.h, src/cpp/include/CPPFORT/lcclu.h, src/cpp/include/CPPFORT/lccol.h, src/cpp/include/CPPFORT/lcevt.h, src/cpp/include/CPPFORT/lcgob.h, src/cpp/include/CPPFORT/lciof77apiext.h, src/cpp/include/CPPFORT/lcmcp.h, src/cpp/include/CPPFORT/lcobv.h, src/cpp/include/CPPFORT/lcpid.h, src/cpp/include/CPPFORT/lcrcp.h, src/cpp/include/CPPFORT/lcrdr.h, src/cpp/include/CPPFORT/lcrdrrep.h, src/cpp/include/CPPFORT/lcrel.h, src/cpp/include/CPPFORT/lcrhd.h, src/cpp/include/CPPFORT/lcrnv.h, src/cpp/include/CPPFORT/lcsch.h, src/cpp/include/CPPFORT/lcsth.h, src/cpp/include/CPPFORT/lctph.h, src/cpp/include/CPPFORT/lctrh.h, src/cpp/include/CPPFORT/lctrk.h, src/cpp/include/CPPFORT/lcvec.h, src/cpp/include/CPPFORT/lcvtx.h, src/cpp/include/CPPFORT/lcwrt.h, src/f77/CMakeLists.txt, src/f77/lciof77api.inc, src/f77/simjob.F, src/f77/simjob_chain.F
- Deprecate the C-API which is used by the fortran interface. However, since no one seems to be actively using that interface we introduce a deprecation warning for the C-API to see if that has any users outside of the internal fortran interface. **If you are seeing deprecation messages in your build outputs please let us know.**
- Fix F77 tests and run them in the CI.
- Degrade some compiler errors back to warnings for gcc10 as it has become more strict than previous versions.
The `SimTrackerHitImpl::setCellID` function does not exist in cpp, so it probably shouldn't exist for the fortran API either. Also added the non-deprecated `lcsthgetcellid0` and `lcsthgetcellid1` to the API (implementations were already present).
=> Deprecate C-API

CMakeLists.txt, src/aid/EVENT/LCParameters.aid, src/aid/EVENT/Vertex.aid, src/cpp/include/IMPL/LCParametersImpl.h, src/cpp/include/pre-generated/EVENT/LCParameters.h, src/cpp/src/EXAMPLE/simjob.cc, src/cpp/src/IMPL/LCParametersImpl.cc, src/cpp/src/SIO/SIOLCParameters.cc, src/cpp/src/UTIL/LCTOOLS.cc, src/java/hep/lcio/implementation/event/ILCParameters.java, src/java/hep/lcio/implementation/sio/SIOLCParameters.java
- add support for storing double values in LCParameters
- used in run, event and collection parameters
- example 
```cpp
DoubleVec dv ;
dv.push_back( 1.111111111111111111111111111111111111111111111111 ) ;
dv.push_back( 2.222222222222222222222222222222222222222222222222 ) ;
dv.push_back( 3.333333333333333333333333333333333333333333333333 ) ;
evt->parameters().setValues( "SomeDoubleNumbers" , dv ) ;
```
- should resolve #138 
=> add double values to LCParameters

.github/workflows/python_bindings.yml, examples/python/readMCParticles.py, setup.sh, sio/CMakeLists.txt, src/cpp/CMakeLists.txt
- Install all the necessary headers to make the python bindings work, even if the sources are removed after installation. Fixes #106
=> Install all headers that are necessary for python bindings

CMakeLists.txt
- Make c++17 the default and minimum c++ version for building LCIO. All "major builds" of LCIO have been using c++17 for at least a few years now, so this should not be a big issue.
=> Bump minimum and default c++ version to 17

src/cpp/src/UTIL/lXDR.cc
- Fix a compiler warning about `strncpy` usage
There is this warning when compiling:
``` shell
LCIO/src/cpp/src/UTIL/lXDR.cc: In member function ‘void UTIL::lXDR::setFileName(const char*, bool)’:
LCIO/src/cpp/src/UTIL/lXDR.cc:78:11: warning: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
78 |    strncpy(_fileName, filename, n);
|    ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
LCIO/src/cpp/src/UTIL/lXDR.cc:76:18: note: length computed here
76 |    int n = strlen(filename);
```
this is being picky about how the copying is done, because we can use `strncpy` to copy the `\0` character without having to do it manually (`strncpy` will put the `\0` once it exhausts …
=> Fix compiler warning

src/cpp/include/UTIL/LCRelationNavigator.h, src/cpp/src/UTIL/LCRelationNavigator.cc
Make getMaxWeight functionality templated that allows passing any comparator. Moving track/caluster weight encodings functionality into MarlinUtil
Added with LCIO v02-18 (https://github.com/iLCSoft/LCIO/releases/tag/v02-18) utility methods to extract the highest weight for LCRelationNavigator are not working properly.
1. `getMaxWeightIt()` must return max_element in every if branch, otherwise passed "weight" parameter is just ignored
https://github.com/iLCSoft/LCIO/blob/2a0d5d14182888486c06f54ccb49b354856286b0/src/cpp/src/UTIL/LCRelationNavigator.cc#L72-L81
2. Every new function that uses `std::string& weightType` as an argument, must have an empty string as a default.
We have discussed with @tmadlener that it would be nice to keep the functionality as general as possible in LCIO and have …
=> Fix bug and change interface of getMaxWeight and move track/cluster encoding parts to MarlinUtil

tests/CMakeLists.txt
- Add test dependencies so that tests can run in parallel 
Fixes #157. I have tried several times and I don't get any failures now when running them in parallel (I didn't run the Java tests). I didn't do the fortran ones because of #151 and #161
=> Add test dependencies

.github/workflows/python.yml
- Upgrade `python-lint` workflow to run on `ubuntu-lates` since `ubuntu-18.04` runners have been removed.
=> Use ubuntu-latest for pylint github action

src/cpp/include/UTIL/CheckCollections.h, src/cpp/src/EXAMPLE/check_missing_cols.cc, src/cpp/src/UTIL/CheckCollections.cc
- Fixes to the on the fly collection patching that are necessary for the LCIO to EDM4hep standalone conversion.
- Make `CheckCollections` check the `FromType` and `ToType` collection parameters to figure out the involved types for `LCRelations`. Add them to the output of `CheckCollections::print`
- Make the `CheckCollectoins::patchCollections` parse these strings back for `LCRelation` collections and set them as collection parameters for collections it creates on the fly.
- Add a `--minimal` flag to `check_missing_cols` in order to make it possible to produce outputs that can be more easily consumbed by other programs.
=> Make proper patching of LCRelations possible

.github/workflows/key4hep.yml, .github/workflows/linux.yml, .github/workflows/python.yml, .github/workflows/python_bindings.yml, src/cpp/include/IMPL/AccessChecked.h, src/cpp/include/IMPL/TrackStateImpl.h, src/cpp/include/UTIL/LCFourVector.h, src/cpp/include/UTIL/LCFourVector.icc, src/cpp/include/UTIL/LCWarning.h, src/cpp/include/pre-generated/EVENT/CalorimeterHit.h, src/cpp/include/pre-generated/EVENT/LCObject.h, src/cpp/include/pre-generated/EVENT/TrackState.h, src/cpp/src/EXAMPLE/lcio_io_benchmark.cc, src/cpp/src/IMPL/TrackStateImpl.cc, tests/CMakeLists.txt
- Add Key4hep release based CI workflow
- Fix remaining warnings to enable `-Werror`
- Update *checkout* action to v3, since v2 is deprecated. 
- **CLHEP >= 2.0** is now required for building the examples that use CLHEP functionality (`test_fourvector`).
=> Add Key4hep based CI workflow

src/cpp/include/UTIL/LCRelationNavigator.h
As a result from discussion in https://github.com/iLCSoft/MarlinReco/pull/114#discussion_r1226258653
I was also thinking of changing `getRelatedToMaxWeight` and friends to call this and to then just return the respective entry of the tuple to have less of a logic duplication but I have no idea how this will affect the performance...
- LCRelationNavigator: add methods `getRelatedToMaxWeightAndObject` and `getRelatedFromMaxWeightAndObject` returning both the object and the weight in a tuple
=> LCRelationNavigator: add methods to return both max weight and object 

cmake/ilcsoft_default_uninstall_target.cmake
- Don't make the uninstall target if it already exists
CMake will throw an error and stop if the uninstall target already exists
=> Don't make the uninstall target if it already exists

CMakeLists.txt, src/cpp/include/IMPL/AccessChecked.h, src/cpp/src/IMPL/TrackImpl.cc
- Fix two compiler warnings with clang
These are the warnings:
``` c++
/LCIO/sio/src/api.cc:497:17: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
rec_buf = std::move( device.take_buffer() ) ;
^
/LCIO/sio/src/api.cc:497:17: note: remove std::move call here
rec_buf = std::move( device.take_buffer() ) ;
^~~~~~~~~~~                     ~~
/LCIO/src/cpp/include/IMPL/AccessChecked.h:25:13: warning: definition of implicit copy constructor for 'AccessChecked' is deprecated because it has a user-declared destructor [-Wdeprecated-copy-with-dtor]
virtual ~AccessChecked() = default;
^
/LCIO/src/cpp/include/IMPL/TrackStateImpl.h:31:5: note: in implicit copy constructor for 'IMPL::AccessChecked' first required here …
```
=> Fix two compiler warnings

CMakeLists.txt
- Bump the minimum CMake version to 3.14
Right now, when running `cmake ..` I get the following warning:
``` shell
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
PROJECT_VERSION
PROJECT_VERSION_MAJOR
PROJECT_VERSION_MINOR
PROJECT_VERSION_PATCH
```
The old behaviour of having the variables is deprecated as explained here:
https://cmake.org/cmake/help/latest/policy/CMP0048.html so it may be removed in
the future but for using the new behavior we need CMake 3.0 (released in 2014).
How `VERSION` works inside `project()` is explained here: …
=> Bump the minimum CMake version

.github/workflows/key4hep.yml, .github/workflows/linux.yml, CMakeLists.txt, cmake/LCIOConfig.cmake.in, tests/downstream-project-cmake-test/CMakeLists.txt, tests/downstream-project-cmake-test/lcio_test_program.cpp
- Make sure that LCIO installations can be used in downstream projects if they are built with builtin SIO. Fixes https://github.com/iLCSoft/LCIO/issues/183
- Add a test to make sure that this works as intended
- Bump the minimum required version for SIO to v00-01 in order to have CMake targets available.
This was probably broken in #177 and (accidentally) fixed by #181 again. This PR essentially just cleans up the `LCIOConfig.cmake.in` which has become possible after #181 (and was missed there).
=> Make sure that LCIO installations are cleanly consumable with builtin SIO

src/cpp/include/SIO/SIOReader.h, src/cpp/include/pre-generated/IO/LCReader.h
Was previously quoted as `LCIO::Update` while it is defined as ::UPDATE in `src/cpp/src/IMPL/LCIO.cc`.
Also precised that it lives in `EVENT::LCIO` namespace.
=> Correct case for SIOReader and LCReader "UPDATE" accessMode in docstrings.

.github/workflows/key4hep.yml
- Switch to c++20 for the key4hep nightlies based CI
=> Use c++20 on key4hep nightlies in CI

.github/workflows/key4hep.yml, src/cpp/include/UTIL/CollectionParameterMap.h, src/cpp/include/UTIL/PIDHandler.h, src/cpp/src/UTIL/PIDHandler.cc
- Make the `PIDHandler` usable as `const` object by marking getters that do not mutate internal state as `const`
=> Make PIDHandler usable as a const object

src/java/hep/lcio/implementation/sio/SIOTrack.java
Fixes https://gitlab.spack.io/spack/spack/-/jobs/11656362
- fix: parentheses in SIOTrack.java
=> fix: parentheses in SIOTrack.java

src/cpp/src/IOIMPL/LCEventLazyImpl.cc
Using `std::remove_if` alone only does some rearranging and changing elements of `_blocks`, and that doesn't seem what's intended there. If everyone is using C++20 `std::erase_if` can be used instead of the `erase - remove` idiom.
- Fix possibly wrong behavior with `std::remove_if` with a `erase - remove` idiom
=> Fix possibly wrong behavior with `std::remove_if`

.github/workflows/key4hep.yml
- Run Key4hep CI workflows on OSs that are still supported
=> Run key4hep CI workflows on still supported OSs

.gitignore
- Add a basic `.gitignore` file to avoid accidentally comitting configured / generated files
=> Add a basic .gitignore file

CMakeLists.txt
- Make sure to require a version of SIO that is consistent with what we would use to build an internal version.
=> Require consistent versions for SIO

src/cpp/include/UTIL/CheckCollections.h, src/cpp/src/UTIL/CheckCollections.cc
- Add functionality to `CheckCollections` that makes it possible to add missing ParticleID algorithms to ReconstructedParticle collections
- This makes it possible to make very consistent event contents that are necessary for conversion to EDM4hep
This is another ingredient for fixing https://github.com/lcfiplus/LCFIPlus/issues/69
=> Make it possible to patch ParticleID meta information when patching collections

src/cpp/src/EXAMPLE/dumpmctree-dot.cc
- Fix compilation on MacOS by adding missing include in dumpmctree-dot.cc
=> fix missing includes

src/cpp/include/UTIL/CheckCollections.h, src/cpp/src/UTIL/CheckCollections.cc
- Make it possible to create empty subset collections during patching
- Appending a **`*`** (star) to the collection type name (no spaces) will make this collection an empty subset collection if it is not already present.
- Fixes [#199 ](https://github.com/iLCSoft/LCIO/issues/199)
=> Make it possible to create subset collections during collection patching

src/cpp/include/UTIL/LCRelationNavigator.h
- Make `getRelatedToMaxWeightAndObject()`, `getRelatedToMaxWeightObject()`, `getRelatedFromMaxWeightObject()` return non-const `LCObject` pointer.
=> Harmonize const-ness in relation navigation return types

CMakeLists.txt
- Add LANGUAGES CXX in the top level CMakeLists.txt to prevent checking for a C compiler.
=> Add LANGUAGES CXX in the top level CMakeLists.txt to prevent checking for a C compiler.

CMakeLists.txt
- Allow building with C++23
The LCG stacks with GCC 15 use C++23
=> Allow building with C++23
